"""GetRich backtesting framework public API."""

from gr_backtest.account import (
    Account,
    MarginState,
    SubAccount,
    SubAccountSnapshot,
    daily_settle,
    get_settlement_prices,
)
from gr_backtest.analytics import (
    compute_ic,
    compute_rank_ic,
    factor_evaluation_report,
)
from gr_backtest.api import (
    AccountError,
    AccountView,
    AssetClass,
    Backtest,
    BacktestError,
    BacktestResult,
    BarContext,
    BarLoader,
    BarSchemaError,
    Context,
    CorporateActionError,
    DataFrameBarLoader,
    DataLoadError,
    DuckDBBarLoader,
    Exchange,
    ExecutionError,
    Fill,
    Frequency,
    HistoryView,
    Money,
    NextBarMatchingModel,
    Order,
    OrderIntent,
    OrderIntentError,
    OrderStatus,
    OrderType,
    PgBarLoader,
    Position,
    PositionView,
    Quantity,
    RunConfig,
    Side,
    Strategy,
    StrategyError,
    Symbol,
    TakeProfitStopLoss,
    TimeInForce,
    TimezoneError,
    ensure_shanghai_aware,
    get_shanghai_tz,
    normalize_datetime_range,
    require_shanghai_aware,
    validate_bar_schema,
)
from gr_backtest.attribution import (
    DEFAULT_ASHARE_SESSIONS,
    DEFAULT_FUTURES_SESSIONS,
    AttributionError,
    FactorExposure,
    FactorRegResult,
    Session,
    SessionAttributionResult,
    SessionStats,
    compute_brinson_attribution,
    compute_cost_attribution,
    compute_factor_regression,
    compute_pnl_attribution,
    compute_session_attribution,
    compute_trade_journal,
)
from gr_backtest.benchmark import (
    Benchmark,
    BenchmarkCompareResult,
    BenchmarkError,
    compute_benchmark_comparison,
)
from gr_backtest.calendar import Calendar
from gr_backtest.cost import (
    BpsSlippage,
    CompositeFee,
    FeeModel,
    FixedFee,
    FixedSlippage,
    PercentageFee,
    PerShareFee,
    SlippageModel,
    ZeroFee,
    ZeroSlippage,
)
from gr_backtest.data import (
    CORP_ACTIONS_OPTIONAL_COLUMNS,
    CORP_ACTIONS_REQUIRED_COLUMNS,
    FACTOR_OPTIONAL_COLUMNS,
    FACTOR_REQUIRED_COLUMNS,
    VALID_ACTION_TYPES,
    resample_bars,
    validate_corp_actions_schema,
    validate_factor_schema,
)
from gr_backtest.exceptions import MarginError, RetryableError, TerminalError
from gr_backtest.margin import MarginCalculator
from gr_backtest.metrics import (
    BacktestMetrics,
    MetricsError,
    compute_metrics,
    monthly_returns_heatmap,
)
from gr_backtest.persistence import (
    BacktestArtifact,
    BacktestPersistenceError,
    PgBacktestResultStore,
    artifacts_from_report_dir,
)
from gr_backtest.report import Reporter, TearSheet
from gr_backtest.result import CombinedResult, ResultView
from gr_backtest.risk import LiquidationEvent, RiskConfig, RiskManager
from gr_backtest.strategy import set_ctx_corp_actions, set_ctx_factors
from gr_backtest.strategy.alloc_weight import (
    BlackLitterman,
    InverseVol,
    MeanVariance,
    RiskParity,
    ScoreWeight,
)
from gr_backtest.strategy.allocator import FixedAllocator
from gr_backtest.strategy.portfolio import (
    Constraints,
    EqualWeight,
    PeriodicRebalance,
    Portfolio,
)
from gr_backtest.strategy.preprocessor import (
    MissingValue,
    Neutralize,
    PreprocessingError,
    SignalPreprocessor,
    Standardize,
    Winsorize,
)
from gr_backtest.strategy.signal import SignalStrategy
from gr_backtest.strategy.target_position import TargetPositionStrategy
from gr_backtest.sweep import (
    GridSearch,
    P,
    ParamSpace,
    ProgressCallback,
    SweepResult,
    SweepRunner,
    SweepTrial,
    SweepTrialResult,
)
from gr_backtest.sweep_persistence import PgSweepResultStore, SweepPersistenceError
from gr_backtest.types import FREQ_TO_MINUTES
from gr_backtest.walk_forward import (
    WalkForward,
    WalkForwardResult,
    WalkForwardRunSpec,
    WalkForwardWindow,
    WalkForwardWindowResult,
)
from gr_backtest.walk_forward_persistence import (
    PgWalkForwardResultStore,
    WalkForwardPersistenceError,
    walk_forward_windows_to_frame,
)
from gr_backtest.walk_forward_report import WalkForwardReport


__all__ = [
    "Account",
    "AccountError",
    "AccountView",
    "SubAccount",
    "SubAccountSnapshot",
    "AssetClass",
    "AttributionError",
    "Backtest",
    "BacktestError",
    "BacktestMetrics",
    "BacktestArtifact",
    "BacktestPersistenceError",
    "Benchmark",
    "BenchmarkCompareResult",
    "BenchmarkError",
    "BpsSlippage",
    "CompositeFee",
    "FeeModel",
    "FixedFee",
    "FixedSlippage",
    "PercentageFee",
    "PeriodicRebalance",
    "PgBacktestResultStore",
    "PgBarLoader",
    "PgSweepResultStore",
    "PgWalkForwardResultStore",
    "P",
    "ParamSpace",
    "PerShareFee",
    "Portfolio",
    "PreprocessingError",
    "BacktestResult",
    "BlackLitterman",
    "Calendar",
    "BarContext",
    "BarLoader",
    "BarSchemaError",
    "CombinedResult",
    "Constraints",
    "Context",
    "CorporateActionError",
    "CORP_ACTIONS_OPTIONAL_COLUMNS",
    "CORP_ACTIONS_REQUIRED_COLUMNS",
    "DataFrameBarLoader",
    "DataLoadError",
    "daily_settle",
    "DEFAULT_ASHARE_SESSIONS",
    "DEFAULT_FUTURES_SESSIONS",
    "DuckDBBarLoader",
    "EqualWeight",
    "FixedAllocator",
    "Exchange",
    "ExecutionError",
    "FACTOR_OPTIONAL_COLUMNS",
    "FACTOR_REQUIRED_COLUMNS",
    "FREQ_TO_MINUTES",
    "Fill",
    "Frequency",
    "HistoryView",
    "MetricsError",
    "LiquidationEvent",
    "MissingValue",
    "Money",
    "Neutralize",
    "NextBarMatchingModel",
    "Order",
    "OrderIntent",
    "OrderIntentError",
    "OrderStatus",
    "OrderType",
    "Position",
    "PositionView",
    "Quantity",
    "Reporter",
    "resample_bars",
    "ResultView",
    "RiskConfig",
    "RiskManager",
    "SweepPersistenceError",
    "SweepResult",
    "ProgressCallback",
    "SweepRunner",
    "SweepTrial",
    "SweepTrialResult",
    "TearSheet",
    "monthly_returns_heatmap",
    "SlippageModel",
    "SignalPreprocessor",
    "SignalStrategy",
    "Standardize",
    "ZeroFee",
    "ZeroSlippage",
    "RunConfig",
    "set_ctx_corp_actions",
    "set_ctx_factors",
    "Side",
    "Strategy",
    "StrategyError",
    "Symbol",
    "TakeProfitStopLoss",
    "TargetPositionStrategy",
    "TimeInForce",
    "TimezoneError",
    "VALID_ACTION_TYPES",
    "validate_corp_actions_schema",
    "validate_factor_schema",
    "WalkForward",
    "WalkForwardPersistenceError",
    "WalkForwardReport",
    "WalkForwardResult",
    "WalkForwardRunSpec",
    "WalkForwardWindow",
    "WalkForwardWindowResult",
    "Winsorize",
    "InverseVol",
    "MeanVariance",
    "RiskParity",
    "ScoreWeight",
    "Session",
    "SessionAttributionResult",
    "SessionStats",
    "__version__",
    "artifacts_from_report_dir",
    "compute_benchmark_comparison",
    "compute_brinson_attribution",
    "compute_cost_attribution",
    "compute_ic",
    "compute_metrics",
    "compute_pnl_attribution",
    "compute_rank_ic",
    "compute_session_attribution",
    "compute_trade_journal",
    "ensure_shanghai_aware",
    "factor_evaluation_report",
    "get_settlement_prices",
    "get_shanghai_tz",
    "GridSearch",
    "MarginCalculator",
    "MarginError",
    "MarginState",
    "normalize_datetime_range",
    "RetryableError",
    "TerminalError",
    "require_shanghai_aware",
    "validate_bar_schema",
    "walk_forward_windows_to_frame",
    # Live signal production
]

__version__ = "0.2.0"


# 已迁出本包的符号（保留说明，便于排查 ImportError）：
#   实盘信号生产 Signal / SignalProducer / SignalWriter / EvalSignalWriter
#     / LiveSignalError / SignalProductionError  -> gr_signal.live
#   回测作业队列 PgBacktestJobStore / BacktestJobError -> gr_api.jobs.persistence
# 回测引擎是最底层的库，不依赖 gr-api 与 gr-signal；反向 import 会把
# FastAPI、Celery 拖进纯计算路径，也会让单独安装 gr-backtest 直接失败。
