# --- 数据库配置 (Database Configuration) ---
default_database:
  host : 192.168.1.60
  port : 8123
  user : default
  password : getrich
  database : default
  timeout : 30

checkpoint:
  duckdb_path : "E://data//etl.parquet"
