-- 015_signals.sql
-- Signals and signal_batches tables.
--
-- Schema-qualified: the backend pool sets SET search_path=app,market,meta,public;
-- services/signals.py references these tables unprefixed.

CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE IF NOT EXISTS app.signals (
    id                  UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    signal_code         VARCHAR(64)     NOT NULL,
    strategy_id         UUID            NOT NULL,
    batch_id            UUID,
    parent_signal_id    UUID,
    market              VARCHAR(32)     NOT NULL,
    exchange            VARCHAR(32),
    symbol              VARCHAR(32)     NOT NULL,
    symbol_name         VARCHAR(255),
    type                VARCHAR(32)     NOT NULL,
    action              VARCHAR(16)     NOT NULL,
    direction           VARCHAR(8),
    entry_low           NUMERIC,
    entry_high          NUMERIC,
    trigger_price       NUMERIC,
    target_price        NUMERIC,
    stop_loss_price     NUMERIC,
    suggested_quantity  INTEGER,
    position_pct        NUMERIC,
    confidence          NUMERIC         NOT NULL DEFAULT 0.50,
    urgency             VARCHAR(16)     NOT NULL DEFAULT 'normal',
    reason              TEXT,
    reason_detail       JSONB           NOT NULL DEFAULT '{}',
    logic_summary       TEXT,
    option_type         VARCHAR(32),
    strike_price        NUMERIC,
    expiry_date         DATE,
    greeks              JSONB,
    access_tier         SMALLINT        NOT NULL DEFAULT 0,
    delay_free_hours    INTEGER,
    status              VARCHAR(16)     NOT NULL DEFAULT 'active',
    expire_at           TIMESTAMPTZ,
    published_at        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    result              VARCHAR(16),
    exit_price          NUMERIC,
    pnl_pct             NUMERIC,
    resolved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.signal_batches (
    id              UUID            PRIMARY KEY DEFAULT gen_random_uuid(),
    strategy_id     UUID            NOT NULL,
    batch_code      VARCHAR(64)     NOT NULL,
    note            TEXT,
    published_at    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_signals_strategy ON app.signals(strategy_id, published_at DESC);
CREATE INDEX IF NOT EXISTS idx_signals_code ON app.signals(signal_code);
CREATE INDEX IF NOT EXISTS idx_signal_batches_strategy ON app.signal_batches(strategy_id, published_at DESC);

COMMENT ON TABLE app.signals IS
    'Trading signals generated by strategies — one row per signal.';
COMMENT ON TABLE app.signal_batches IS
    'Batch grouping for signals published together.';
