"""HTML sanitization for user-supplied rich content.

This module is the **second** of three layers of defense against stored XSS
on `strategies.detail_html` (and any other user-authored rich text we add
later):

  1. **Schema** — `migrations/024_*.sql` caps the column at 50,000 chars
     via a Postgres `CHECK` constraint (the database will reject oversized
     writes even if both the form and the service are bypassed).
  2. **Service** — this module strips dangerous tags/attributes/URIs from
     the value **before** it lands in the database. Any caller that
     persists `detail_html` must run it through `normalize_detail_html`
     first (see `services/strategy.py::update_strategy`).
  3. **Render** — `frontend/src/lib/sanitize.ts::sanitizeHtml()` runs
     DOMPurify at the call site of `dangerouslySetInnerHTML`. Even if
     both the schema and the service are bypassed, the browser will
     refuse to execute the sanitized HTML.

The allow-list intentionally rejects:
  - `<script>`, `<style>`, `<iframe>`, `<object>`, `<embed>` and any other
    tag that can execute script or load remote content.
  - All event handler attributes (`onclick`, `onerror`, `onload`, …).
  - Dangerous URI protocols: `javascript:`, `data:`, `vbscript:`. Only
    `http`, `https`, and `mailto` are permitted; relative URIs are kept
    when bleach's `ALLOWED_URI_REGEXP` is in effect (we pass an explicit
    regex below to keep them).

Bleach's `clean()` with `strip=True` mirrors DOMPurify's default: drop
the dangerous tag entirely, keep its text content. We deliberately do
NOT escape the text (Bleach's other default), so `<script>alert(1)</script>`
becomes the literal text "alert(1)" — same as the frontend helper.

`signals.reason` is **plain text** (not HTML): the live signal
producer generates an algorithmic explanation like
"MA(5) crossed above MA(20) with Z-score 2.3" — never HTML.
`normalize_reason()` runs the same bleach strip with an empty
tag allow-list so any `<script>` / `<img onerror>` payload that
somehow lands in the column is reduced to literal text. This is
defense in depth: the frontend already renders `{signal.reason}`
as a text node (React escapes it), and the DB CHECK in
`migrations/025_signals_reason_length.sql` caps the column at
`MAX_REASON_LENGTH` chars.
"""

from __future__ import annotations

import bleach


# Tags allowed in the rendered detail. Limited to semantic content — no
# interactive or script-capable elements. Kept in lock-step with
# `frontend/src/lib/sanitize.ts::ALLOWED_TAGS`.
_ALLOWED_TAGS: list[str] = [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "p",
    "br",
    "hr",
    "ul",
    "ol",
    "li",
    "strong",
    "em",
    "b",
    "i",
    "u",
    "code",
    "pre",
    "blockquote",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    "a",
    "img",
]

# Per-tag attribute allow-list. Kept in lock-step with
# `frontend/src/lib/sanitize.ts::ALLOWED_ATTR`.
_ALLOWED_ATTRS: dict[str, list[str]] = {
    "a": ["href", "title"],
    "img": ["src", "alt", "title"],
    "th": ["colspan", "rowspan"],
    "td": ["colspan", "rowspan"],
}

# URI protocol allow-list — `http`, `https`, `mailto`, plus same-origin
# relative paths. Rejects `javascript:`, `data:`, `vbscript:`, etc.
_ALLOWED_PROTOCOLS: list[str] = ["http", "https", "mailto"]
_ALLOWED_URI_REGEXP = r"^(?:https?:|mailto:|/(?!/))"

# Hard cap on the column (matched by the Postgres CHECK constraint in
# `migrations/024_*.sql` and by the frontend zod schema in
# `frontend/src/pages/StrategyEdit.tsx`).
MAX_LENGTH: int = 50_000

# Hard cap on `signals.reason` (plain text). Matched by the Postgres
# CHECK in `migrations/025_signals_reason_length.sql`. 2 000 chars is
# enough for a 5-10 sentence algorithmic explanation; anything longer
# is almost certainly a bug or an injection attempt.
MAX_REASON_LENGTH: int = 2_000


def normalize_detail_html(raw: str | None) -> str:
    """Strip dangerous content from a user-supplied HTML string.

    Returns `""` for `None` / empty input. Otherwise returns the cleaned
    HTML with the allow-list above, capped at `MAX_LENGTH` chars.

    The output is safe to persist to the `detail_html` column. The
    frontend will *also* sanitize on render (`sanitizeHtml`); both
    layers are intentional defense in depth.
    """
    if not raw:
        return ""
    cleaned = bleach.clean(
        raw,
        tags=_ALLOWED_TAGS,
        attributes=_ALLOWED_ATTRS,
        protocols=_ALLOWED_PROTOCOLS,
        strip=True,
    )
    if len(cleaned) > MAX_LENGTH:
        cleaned = cleaned[:MAX_LENGTH]
    return cleaned


def normalize_reason(raw: str | None) -> str:
    """Strip any HTML from a `signals.reason` value.

    The field is plain text by contract (generated by the live signal
    producer), but this helper runs bleach with an empty tag
    allow-list so any payload that lands in the column through a
    future write path is reduced to literal text before it reaches
    the API response. Combined with the frontend's text-node render
    (`{signal.reason}`) and the DB CHECK constraint, this is the
    third layer of XSS defense on the field.

    Returns `""` for `None` / empty input. Otherwise returns the
    cleaned plain text, capped at `MAX_REASON_LENGTH` chars.
    """
    if not raw:
        return ""
    # Empty tag set + ``strip=True`` removes every tag but keeps the
    # text content. ``strip_comments=True`` drops ``<!-- ... -->``
    # which would otherwise survive the empty allow-list.
    cleaned = bleach.clean(
        raw,
        tags=[],
        attributes={},
        protocols=[],
        strip=True,
        strip_comments=True,
    )
    if len(cleaned) > MAX_REASON_LENGTH:
        cleaned = cleaned[:MAX_REASON_LENGTH]
    return cleaned


__all__ = [
    "MAX_LENGTH",
    "MAX_REASON_LENGTH",
    "normalize_detail_html",
    "normalize_reason",
]
